name: CI
on:
  push:
    branches: [ main ]
jobs:
  publish:
    runs-on: ubuntu-latest
    container:
      image: jgoldfar/pandoc-nbconvert-docker
      options: --cpus 1
    steps:
      - uses: actions/checkout@v2
      - name: Convert notebooks
        run: (jupyter nbconvert --to html --template lab *.ipynb --output-dir html)
      - name: Fix links
        run: (sed -i 's/\.ipynb/\.html/g' ./html/*.html)
      - name: Azure Static Web Apps Deploy
        uses: Azure/static-web-apps-deploy@v1
        with:
          action: upload
          app_location: html 
          azure_static_web_apps_api_token: ${{secrets.TOKEN}}
          skip_app_build: true
                        
