name: CI
on:
  push:
    branches: [ main ]
jobs:
  container-test-job:
    runs-on: ubuntu-latest
    container:
      image: jgoldfar/pandoc-nbconvert-docker
      options: --cpus 1
    steps:
      - uses: actions/checkout@v2
      - name: Convert notebooks
        run: (jupyter nbconvert --to html  *.ipynb --output-dir html)
